postgres:
  user: postgres
  host: postgres
  port: 5432
  database: my_db
  password: 1234
rabbitmq:
  user: guest
  password: guest
  host: rabbit
  port: 5672
mongodb:
  host: mongo
  port: 27017
  database: my_db